### ISSUE TITLE
Android - Instant CRASH - No log

### ISSUE THREAD

**Issue by applauzmedia** [myflashlab/ANE-LAB#143]
I've set a project up for iOS and Android.  iOS runs bug free. Android crashes when trying to open the app. No explanation for the crash is given.

**Comment by applauzmedia** [comment]
Went in to the Device Logs and found the follwing.

`01-25 00:23:52.883  1303  1334 I ActivityManager: Start proc 11927:air.com.testproject/u0a281 for activity {air.com.testproject/air.com.testproject.AppEntry}
01-25 00:23:52.883  9881  9924 I AssistantForeground: Get launcher package: com.google.android.apps.nexuslauncher
01-25 00:23:52.884 11927 11927 E .testproject: Not starting debugger since process cannot load the jdwp agent.
01-25 00:23:52.885  1664  1664 W NgaUiController: Unknown action "screen_state"; cannot process RPC
01-25 00:23:52.898 11927 11927 W .testproject: resources.arsc in APK '/data/app/air.com.testproject-ugJNbrbOlRU4gZtQvnYOgw==/base.apk' is compressed.
01-25 00:23:52.904 11927 11927 I MultiDex: VM with version 2.1.0 has multidex support
01-25 00:23:52.904 11927 11927 I MultiDex: Installing application
01-25 00:23:52.904 11927 11927 I MultiDex: VM has multidex support, MultiDex support library is disabled.
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: Class com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar is not an found.
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at java.lang.Class.classForName(Native Method)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at java.lang.Class.forName(Class.java:454)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at java.lang.Class.forName(Class.java:379)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-components@@16.0.0:80)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-components@@16.0.0:73)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@19.3.0:404)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:300)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.os.Looper.loop(Looper.java:214)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at java.lang.reflect.Method.invoke(Native Method)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: Caused by: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar
01-25 00:23:52.906 11927 11927 W ComponentDiscovery: 	... 24 more
01-25 00:23:52.914 11927 11927 I FirebaseInitProvider: FirebaseApp initialization successful
01-25 00:23:52.929 11927 11955 E AndroidRuntime: FATAL EXCEPTION: Thread-2
01-25 00:23:52.929 11927 11955 E AndroidRuntime: Process: air.com.testproject, PID: 11927
01-25 00:23:52.929 11927 11955 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/measurement/api/AppMeasurementSdk;
01-25 00:23:52.929 11927 11955 E AndroidRuntime: 	at com.google.android.gms.internal.ads.zzamj.zze(com.google.android.gms:play-services-ads-lite@@19.2.0:41)
01-25 00:23:52.929 11927 11955 E AndroidRuntime: 	at com.google.android.gms.internal.ads.zzami.run(Unknown Source:4)
01-25 00:23:52.929 11927 11955 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
01-25 00:23:52.929 11927 11955 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.measurement.api.AppMeasurementSdk
01-25 00:23:52.929 11927 11955 E AndroidRuntime: 	... 3 more
01-25 00:23:52.929 11927 11927 I StartupTime1: :1611552232929
01-25 00:23:52.929 11927 11927 I AIR VERSION: :33.1.1.300
01-25 00:23:52.929 11927 11927 I DEVICE ARCH: :arm64-v8a
`

**Comment by Gokulv617** [comment]
NOTE: The AIR version 33.1.1.300 is not stable. It causes many crashes. Can you check in the latest AIR 33.1.1.345 ?

**Comment by applauzmedia** [comment]
Tried with AIR version 33.1.1.345     Same error.

`01-25 08:36:32.758 24409 24436 E AndroidRuntime: FATAL EXCEPTION: Thread-2
01-25 08:36:32.758 24409 24436 E AndroidRuntime: Process: air.com.testproject, PID: 24409
01-25 08:36:32.758 24409 24436 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/measurement/api/AppMeasurementSdk;
01-25 08:36:32.758 24409 24436 E AndroidRuntime: 	at com.google.android.gms.internal.ads.zzamj.zze(com.google.android.gms:play-services-ads-lite@@19.2.0:41)
01-25 08:36:32.758 24409 24436 E AndroidRuntime: 	at com.google.android.gms.internal.ads.zzami.run(Unknown Source:4)
01-25 08:36:32.758 24409 24436 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
01-25 08:36:32.758 24409 24436 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.measurement.api.AppMeasurementSdk
01-25 08:36:32.758 24409 24436 E AndroidRuntime: 	... 3 more
`

**Comment by myflashlab** [comment]
@applauzmedia based on the error message, `Class com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar is not an found.`

the dependency ANE which includes that class is [googlePlayServices_measurementBase.ane](https://github.com/myflashlab/common-dependencies-ANE/blob/master/googlePlayServices/googlePlayServices_measurementBase.ane) are you sure that ANE is included? and also implemented in your project?

**Comment by applauzmedia** [comment]
@myflashlab Yes this file is added.  ANE LAB Adds this file.  I also added to be safe.  Is there anything else I need to add?  It still crashes right away.

`import com.myflashlab.air.extensions.dependency.GooglePlayServices_measurementBase;`

<img width="382" alt="Screen Shot 2021-01-28 at 8 43 11 AM" src="https://user-images.githubusercontent.com/40473682/106146847-2ff2a180-6145-11eb-83b3-21eef3af219e.png">

**Comment by myflashlab** [comment]
@applauzmedia I just had a closer look around this and noticed that `java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar` is not causing the crash. the next line says:

```
FirebaseInitProvider: FirebaseApp initialization successful
```

So, that one can be ignored. however, this one `java.lang.ClassNotFoundException: com.google.android.gms.measurement.api.AppMeasurementSdk` might... the weird thing is that this class is also available in the same dependency so there shouldn't be a problem. 🤔 

Anyway, please zip and send your demo project including the  ANEs, .fla file and the manifest and everything (exclude your registration key in the manifest) and I'll run your project here locally and see what might have gone wrong... let's continue on that.

**Comment by applauzmedia** [comment]
@myflashlab - I don't have a demo project. I only have my main app project.

Do you see anything missing from my manifest extensions?

`<extensions>
        <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.myflashlab.air.extensions.billing</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidx.arch</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidx.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidx.design</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidx.lifecycle</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.addons.firestore</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.addons.squareup</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.auth</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.database.collection</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.firestore</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.installations</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gass</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.stats</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.gson</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.firestore</extensionID>
        <extensionID>com.myflashlab.air.extensions.videoPlayer</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidx.browser</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.addons.fcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.datatransport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.encoders.json</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.location</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.places</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
        <extensionID>com.myflashlab.air.extensions.udid</extensionID>
    </extensions>`

**Comment by myflashlab** [comment]
Hmm, maybe creating a demo project can be super easy, just remove all your app code but keep manifest, app package name and a simple DocumentClass .as file just to duplicate the problem. on that simple demo project, I can run everything and test and help youi get over all these weird troubles.
